{
    "comment": "RTML source syntax highlighting",
    "name": "rtml",
    "scopeName": "source.rtml",
    "fileTypes": ["rtml"],
    "patterns": [
                {
                    "match":"([A-Z]*-+[A-Z]*)",
                    "name":"string.quoted.single.rtml",
                    "captures": {
                        "1": { "name": "string.quoted.single.rtml" }
                    }
                },
                {
                    "match":"(.*?)\\((.*?)\\)",
                    "name":"string.quoted.single.rtml",
                    "captures": {
                        "1": { "name": "string.quoted.single.rtml" },
                        "2":{ "name": "constant.language.rtml" }
                    }
                },
                {
                    "match":"\"(.*?)\"",
                    "name":"string.quoted.double.rtml",
                    "captures": {
                        "1": { "name": "string.quoted.double.rtml" }
                    }
                },
                {
                    "match":"(\\s(id)\\s|up)",
                    "name":"support.constant.rtml"
                },
                {
                    "match":"(name|var|sequence|content)",
                    "name":"variable.parameter.rtml",
                    "captures": {
                        "1": { "name": "variable.parameter.rtml" }
                    }
                },
                {
                    "match":"(value[\\d]?)",
                    "name":"constant.language.rtml",
                    "captures": {
                        "1": {"name":"constant.language.rtml"}
                    }
                },
                {
                    "match":"(nil|source|tag|alt|class|title|clear|number|test|then|else|variable|sequence|last|border|cellpadding|cellspacing|valign|align|width|height)",
                    "name":"constant.language.rtml",
                    "captures": {
                        "1": {"name":"constant.language.rtml"}
                    }
                },
                 {
                "match": "(@|:)(\\w+|-|\\d+)+",
                "name": "variable.other.rtml",
                "captures": {
                    "1": { "name": "markup.bold.rtml" },
                    "2":{"name":"variable.other.rtml"}
                    },
                "comment": "Variables @exclusive-seocaption, @exclusive-dnp-txt"
                },

                {
                "match":"(WITH[=]+)",
                "name":"keyword.operator.rtml",
                "comment":"RTML operators"
            },
            {
                "match":":(.*?)\\s",
                "name":"keyword.operator.rtml",
                "comment":"RTML CALL operators",
                "captures": {
                    "1": { "name": "keyword.control.rtml" },
                    "2":{"name":"keyword.control.rtml"}
                }

            },
            {
                "match": "(TEXT|GRAB|MULTI|CALL)|(FOR-EACH-OBJECT|FOR-EACH)|(LOWERCASE|AS-STRING|LINEBREAK|TAG-WHEN|TABLE)|(TITLE|IMG|DIV|META)|(WHEN|IF|NONEMPTY|WITH|AND|OR|NOT|EQUALS)|(CALL)|(LINES|SEGMENTS|TOKENS|LENGTH|ELEMENTS|VALUE|POSITION|PARAGRAPHS|SHIM|RENDER)|(IMAGE)",
                "name": "keyword.operator.rtml",
                "captures":{
                    "0":{"name":"keyword.other.rtml"},
                    "1":{"name":"keyword.operator.rtml"},
                    "2":{"name":"keyword.control.rtml"},
                    "3":{"name":"keyword.operator.rtml"},
                    "4":{"name":"keyword.operator.rtml"},
                    "5":{"name":"keyword.operator.rtml"},
                    "6":{"name":"keyword.operator.rtml"},
                    "7":{"name":"keyword.operator.rtml"},
                    "7":{"name":"storage.type.rtml"}
                },
                "comment": "RTML operators"
            }

  ],
  "uuid": "05d308df-3e52-4717-983f-d5bbcf33ea71"
}