<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>RTML source syntax highlighting</string>
	<key>fileTypes</key>
	<array>
		<string>rtml</string>
	</array>
	<key>name</key>
	<string>rtml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.rtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Z]*-+[A-Z]*)</string>
			<key>name</key>
			<string>string.quoted.single.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.rtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.rtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(.*?)\((.*?)\)</string>
			<key>name</key>
			<string>string.quoted.single.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.rtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>"(.*?)"</string>
			<key>name</key>
			<string>string.quoted.double.rtml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s(id)\s|up)</string>
			<key>name</key>
			<string>support.constant.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.rtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(name|var|sequence|content)</string>
			<key>name</key>
			<string>variable.parameter.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.rtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(value[\d]?)</string>
			<key>name</key>
			<string>constant.language.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.rtml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(nil|source|tag|alt|class|title|clear|number|test|then|else|variable|sequence|last|border|cellpadding|cellspacing|valign|align|width|height)</string>
			<key>name</key>
			<string>constant.language.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold.rtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.rtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variables @exclusive-seocaption, @exclusive-dnp-txt</string>
			<key>match</key>
			<string>(@|:)(\w+|-|\d+)+</string>
			<key>name</key>
			<string>variable.other.rtml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>RTML operators</string>
			<key>match</key>
			<string>(WITH[=]+)</string>
			<key>name</key>
			<string>keyword.operator.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RTML CALL operators</string>
			<key>match</key>
			<string>:(.*?)\s</string>
			<key>name</key>
			<string>keyword.operator.rtml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.rtml</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rtml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rtml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rtml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rtml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rtml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rtml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.type.rtml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>RTML operators</string>
			<key>match</key>
			<string>(TEXT|GRAB|MULTI|CALL)|(FOR-EACH-OBJECT|FOR-EACH)|(LOWERCASE|AS-STRING|LINEBREAK|TAG-WHEN|TABLE)|(TITLE|IMG|DIV|META)|(WHEN|IF|NONEMPTY|WITH|AND|OR|NOT|EQUALS)|(CALL)|(LINES|SEGMENTS|TOKENS|LENGTH|ELEMENTS|VALUE|POSITION|PARAGRAPHS|SHIM|RENDER)|(IMAGE)</string>
			<key>name</key>
			<string>keyword.operator.rtml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rtml</string>
	<key>uuid</key>
	<string>05d308df-3e52-4717-983f-d5bbcf33ea71</string>
</dict>
</plist>
